/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusSchedulerRouteImport } from './routes/status-scheduler'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ForfaitsRouteImport } from './routes/forfaits'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContextRouteImport } from './routes/context'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingReviewProductsRouteImport } from './routes/onboarding.review-products'
import { Route as OnboardingImportRouteImport } from './routes/onboarding.import'
import { Route as OnboardingBusinessInfoRouteImport } from './routes/onboarding.business-info'
import { Route as OnboardingAdvancedOptionsRouteImport } from './routes/onboarding.advanced-options'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthTermsRouteImport } from './routes/auth.terms'
import { Route as AuthProvisioningDebugRouteImport } from './routes/auth.provisioning-debug'
import { Route as AuthProvisioningRouteImport } from './routes/auth.provisioning'
import { Route as AuthPrivacyRouteImport } from './routes/auth.privacy'
import { Route as AuthPairingCodeRouteImport } from './routes/auth.pairing-code'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSchedulerRoute = StatusSchedulerRouteImport.update({
  id: '/status-scheduler',
  path: '/status-scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ForfaitsRoute = ForfaitsRouteImport.update({
  id: '/forfaits',
  path: '/forfaits',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingReviewProductsRoute =
  OnboardingReviewProductsRouteImport.update({
    id: '/onboarding/review-products',
    path: '/onboarding/review-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingImportRoute = OnboardingImportRouteImport.update({
  id: '/onboarding/import',
  path: '/onboarding/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBusinessInfoRoute = OnboardingBusinessInfoRouteImport.update({
  id: '/onboarding/business-info',
  path: '/onboarding/business-info',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAdvancedOptionsRoute =
  OnboardingAdvancedOptionsRouteImport.update({
    id: '/onboarding/advanced-options',
    path: '/onboarding/advanced-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/auth/terms',
  path: '/auth/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProvisioningDebugRoute = AuthProvisioningDebugRouteImport.update({
  id: '/auth/provisioning-debug',
  path: '/auth/provisioning-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProvisioningRoute = AuthProvisioningRouteImport.update({
  id: '/auth/provisioning',
  path: '/auth/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPrivacyRoute = AuthPrivacyRouteImport.update({
  id: '/auth/privacy',
  path: '/auth/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPairingCodeRoute = AuthPairingCodeRouteImport.update({
  id: '/auth/pairing-code',
  path: '/auth/pairing-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/context': typeof ContextRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forfaits': typeof ForfaitsRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/stats': typeof StatsRoute
  '/status-scheduler': typeof StatusSchedulerRoute
  '/support': typeof SupportRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pairing-code': typeof AuthPairingCodeRoute
  '/auth/privacy': typeof AuthPrivacyRoute
  '/auth/provisioning': typeof AuthProvisioningRoute
  '/auth/provisioning-debug': typeof AuthProvisioningDebugRoute
  '/auth/terms': typeof AuthTermsRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/onboarding/advanced-options': typeof OnboardingAdvancedOptionsRoute
  '/onboarding/business-info': typeof OnboardingBusinessInfoRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/review-products': typeof OnboardingReviewProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/context': typeof ContextRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forfaits': typeof ForfaitsRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/stats': typeof StatsRoute
  '/status-scheduler': typeof StatusSchedulerRoute
  '/support': typeof SupportRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pairing-code': typeof AuthPairingCodeRoute
  '/auth/privacy': typeof AuthPrivacyRoute
  '/auth/provisioning': typeof AuthProvisioningRoute
  '/auth/provisioning-debug': typeof AuthProvisioningDebugRoute
  '/auth/terms': typeof AuthTermsRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/onboarding/advanced-options': typeof OnboardingAdvancedOptionsRoute
  '/onboarding/business-info': typeof OnboardingBusinessInfoRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/review-products': typeof OnboardingReviewProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/context': typeof ContextRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forfaits': typeof ForfaitsRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/stats': typeof StatsRoute
  '/status-scheduler': typeof StatusSchedulerRoute
  '/support': typeof SupportRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pairing-code': typeof AuthPairingCodeRoute
  '/auth/privacy': typeof AuthPrivacyRoute
  '/auth/provisioning': typeof AuthProvisioningRoute
  '/auth/provisioning-debug': typeof AuthProvisioningDebugRoute
  '/auth/terms': typeof AuthTermsRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/onboarding/advanced-options': typeof OnboardingAdvancedOptionsRoute
  '/onboarding/business-info': typeof OnboardingBusinessInfoRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/review-products': typeof OnboardingReviewProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/context'
    | '/dashboard'
    | '/faq'
    | '/forfaits'
    | '/leads'
    | '/marketing'
    | '/orders'
    | '/pricing'
    | '/stats'
    | '/status-scheduler'
    | '/support'
    | '/auth/login'
    | '/auth/pairing-code'
    | '/auth/privacy'
    | '/auth/provisioning'
    | '/auth/provisioning-debug'
    | '/auth/terms'
    | '/auth/verify-otp'
    | '/onboarding/advanced-options'
    | '/onboarding/business-info'
    | '/onboarding/import'
    | '/onboarding/review-products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/context'
    | '/dashboard'
    | '/faq'
    | '/forfaits'
    | '/leads'
    | '/marketing'
    | '/orders'
    | '/pricing'
    | '/stats'
    | '/status-scheduler'
    | '/support'
    | '/auth/login'
    | '/auth/pairing-code'
    | '/auth/privacy'
    | '/auth/provisioning'
    | '/auth/provisioning-debug'
    | '/auth/terms'
    | '/auth/verify-otp'
    | '/onboarding/advanced-options'
    | '/onboarding/business-info'
    | '/onboarding/import'
    | '/onboarding/review-products'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/context'
    | '/dashboard'
    | '/faq'
    | '/forfaits'
    | '/leads'
    | '/marketing'
    | '/orders'
    | '/pricing'
    | '/stats'
    | '/status-scheduler'
    | '/support'
    | '/auth/login'
    | '/auth/pairing-code'
    | '/auth/privacy'
    | '/auth/provisioning'
    | '/auth/provisioning-debug'
    | '/auth/terms'
    | '/auth/verify-otp'
    | '/onboarding/advanced-options'
    | '/onboarding/business-info'
    | '/onboarding/import'
    | '/onboarding/review-products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ContextRoute: typeof ContextRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForfaitsRoute: typeof ForfaitsRoute
  LeadsRoute: typeof LeadsRoute
  MarketingRoute: typeof MarketingRoute
  OrdersRoute: typeof OrdersRoute
  PricingRoute: typeof PricingRoute
  StatsRoute: typeof StatsRoute
  StatusSchedulerRoute: typeof StatusSchedulerRoute
  SupportRoute: typeof SupportRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPairingCodeRoute: typeof AuthPairingCodeRoute
  AuthPrivacyRoute: typeof AuthPrivacyRoute
  AuthProvisioningRoute: typeof AuthProvisioningRoute
  AuthProvisioningDebugRoute: typeof AuthProvisioningDebugRoute
  AuthTermsRoute: typeof AuthTermsRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  OnboardingAdvancedOptionsRoute: typeof OnboardingAdvancedOptionsRoute
  OnboardingBusinessInfoRoute: typeof OnboardingBusinessInfoRoute
  OnboardingImportRoute: typeof OnboardingImportRoute
  OnboardingReviewProductsRoute: typeof OnboardingReviewProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-scheduler': {
      id: '/status-scheduler'
      path: '/status-scheduler'
      fullPath: '/status-scheduler'
      preLoaderRoute: typeof StatusSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forfaits': {
      id: '/forfaits'
      path: '/forfaits'
      fullPath: '/forfaits'
      preLoaderRoute: typeof ForfaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/review-products': {
      id: '/onboarding/review-products'
      path: '/onboarding/review-products'
      fullPath: '/onboarding/review-products'
      preLoaderRoute: typeof OnboardingReviewProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/import': {
      id: '/onboarding/import'
      path: '/onboarding/import'
      fullPath: '/onboarding/import'
      preLoaderRoute: typeof OnboardingImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/business-info': {
      id: '/onboarding/business-info'
      path: '/onboarding/business-info'
      fullPath: '/onboarding/business-info'
      preLoaderRoute: typeof OnboardingBusinessInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/advanced-options': {
      id: '/onboarding/advanced-options'
      path: '/onboarding/advanced-options'
      fullPath: '/onboarding/advanced-options'
      preLoaderRoute: typeof OnboardingAdvancedOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/terms': {
      id: '/auth/terms'
      path: '/auth/terms'
      fullPath: '/auth/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/provisioning-debug': {
      id: '/auth/provisioning-debug'
      path: '/auth/provisioning-debug'
      fullPath: '/auth/provisioning-debug'
      preLoaderRoute: typeof AuthProvisioningDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/provisioning': {
      id: '/auth/provisioning'
      path: '/auth/provisioning'
      fullPath: '/auth/provisioning'
      preLoaderRoute: typeof AuthProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/privacy': {
      id: '/auth/privacy'
      path: '/auth/privacy'
      fullPath: '/auth/privacy'
      preLoaderRoute: typeof AuthPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pairing-code': {
      id: '/auth/pairing-code'
      path: '/auth/pairing-code'
      fullPath: '/auth/pairing-code'
      preLoaderRoute: typeof AuthPairingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ContextRoute: ContextRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForfaitsRoute: ForfaitsRoute,
  LeadsRoute: LeadsRoute,
  MarketingRoute: MarketingRoute,
  OrdersRoute: OrdersRoute,
  PricingRoute: PricingRoute,
  StatsRoute: StatsRoute,
  StatusSchedulerRoute: StatusSchedulerRoute,
  SupportRoute: SupportRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPairingCodeRoute: AuthPairingCodeRoute,
  AuthPrivacyRoute: AuthPrivacyRoute,
  AuthProvisioningRoute: AuthProvisioningRoute,
  AuthProvisioningDebugRoute: AuthProvisioningDebugRoute,
  AuthTermsRoute: AuthTermsRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  OnboardingAdvancedOptionsRoute: OnboardingAdvancedOptionsRoute,
  OnboardingBusinessInfoRoute: OnboardingBusinessInfoRoute,
  OnboardingImportRoute: OnboardingImportRoute,
  OnboardingReviewProductsRoute: OnboardingReviewProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
